[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "tara"
authors = [{name = "Amith Kamath", email = "amithjkamath@outlook"}]
dynamic = ["version", "description"]
